### ISSUE TITLE
[Bug] The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by xiaoxstz** [ScoopInstaller/Scoop#6183]
#### Current Behavior

I came across this issue when I updated any package, for example, `vscode` and `oh-my-posh`

I have tried PowerShell (7.4.5) and Cmd, and the outputs are the same like below.

```cmd
d:\Desktop>scoop update oh-my-posh
oh-my-posh: 23.15.3 -> 23.17.0
Updating one outdated app:
Updating 'oh-my-posh' (23.15.3 -> 23.17.0)
Downloading new version
OperationStopped: C:\Users\tanzi\scoop\apps\scoop\current\lib\install.ps1:115
Line |
 115 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

#### Expected Behavior

Download the package and install it.

#### Possible Solution

This issue is the same with #3746 . However, the solutions mentioned in the issue don't work.

I have tried the solutions below, and they all failed.The error information keeps the same.

* Method 1: run the command in PowerShell `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"`
* Mehtod 2: run the update command in CMD. `scoop update oh-my-posh`

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

```PowerShell
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      5
```

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2024-10-11T16:42:25.2438842+08:00",
  "aria2-enabled": false,
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by xiaoxstz** [comment]
Accroding to the output message, I opened the file `install.ps1` and went to Line 115.  Then I add `Write-Host( $e.innerexception)` ahead the line `throw $e`.

After that, I ran the command `scoop update oh-my-posh` to see the inner exception. Then, I got the output below.

```PowerShell
d:\Desktop>scoop update oh-my-posh
oh-my-posh: 23.15.3 -> 23.17.0
Updating one outdated app:
Updating 'oh-my-posh' (23.15.3 -> 23.17.0)
Downloading new version
System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
OperationStopped: C:\Users\tanzi\scoop\apps\scoop\current\lib\install.ps1:116
Line |
 116 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

**Comment by xiaoxstz** [comment]
According to [SecurityProtocol](https://learn.microsoft.com/zh-tw/dotnet/api/system.net.servicepointmanager.securityprotocol?view=net-8.0) and [SecurityProtocolType](https://learn.microsoft.com/zh-tw/dotnet/api/system.net.securityprotocoltype?view=net-8.0), `Ssl3` is deprecated, so I set the SecurityProtocol to `tls`, `tls11`, `tls12`, `tls13`, `SystemDefault` with the command below.

```PowerShell
[Net.ServicePointManager]::SecurityProtocol = "tls, tls11, tls12, tls13, SystemDefault"
```

However, the error information keeps the same.

**Comment by xiaoxstz** [comment]
Today, I restarted my computer, and the issue disappeared. I am not sure which operation worked.

**Comment by k0pernikus** [comment]
I am seeing this today when trying to update imagick:

```
$ scoop update imagemagick
imagemagick: 7.1.2-5 -> 7.1.2-7
Updating one outdated app:
Updating 'imagemagick' (7.1.2-5 -> 7.1.2-7)
Downloading new version
OperationStopped: C:\Users\philipp.kretzschmar\scoop\apps\scoop\current\lib\download.ps1:84
Line |
  84 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

It could update other programs like `everything` before without issue through a `scoop update -a`:

```
$ scoop update -a
...
Scoop was updated successfully!
everything: 1.4.1.1028 -> 1.4.1.1029
feishin: 0.20.1 -> 0.21.2
imagemagick: 7.1.2-5 -> 7.1.2-7
libreoffice: 25.8.1 -> 25.8.2
WARN  error: The remote server returned an error: (404) Not Found.
opera: 122.0.5643.92 -> 122.0.5643.142
telegram: 6.1.4 -> 6.2.3
Updating 6 outdated apps:
Updating 'everything' (1.4.1.1028 -> 1.4.1.1029)
Downloading new version
Downloading https://www.voidtools.com/Everything-1.4.1.1029.x64.zip (1.8 MB)...
Checking hash of Everything-1.4.1.1029.x64.zip ... ok.
Running pre_uninstall script...done.
Uninstalling 'everything' (1.4.1.1028)
Removing shim 'Everything.shim'.
Removing shim 'Everything.exe'.
Unlinking ~\scoop\apps\everything\current
Installing 'everything' (1.4.1.1029) [64bit] from 'extras' bucket
Loading Everything-1.4.1.1029.x64.zip from cache
Extracting Everything-1.4.1.1029.x64.zip ... done.
Running pre_install script...done.
Linking ~\scoop\apps\everything\current => ~\scoop\apps\everything\1.4.1.1029
Creating shim for 'Everything'.
Making C:\Users\philipp.kretzschmar\scoop\shims\everything.exe a GUI binary.
Creating shortcut for Everything (Everything.exe)
Running post_install script...done.
'everything' (1.4.1.1029) was installed successfully!
Notes
-----
To add Everything to right-click context menu, run:
reg import "C:\Users\philipp.kretzschmar\scoop\apps\everything\current\install-c                                                                                                              ontext.reg"
Updating 'feishin' (0.20.1 -> 0.21.2)
Downloading new version
Downloading https://github.com/jeffvli/feishin/releases/download/v0.21.2/Feishin                                                                                                              -0.21.2-win-x64.zip (178.1 MB)...
Checking hash of Feishin-0.21.2-win-x64.zip ... ok.
Uninstalling 'feishin' (0.20.1)
Unlinking ~\scoop\apps\feishin\current
Installing 'feishin' (0.21.2) [64bit] from 'extras' bucket
Loading Feishin-0.21.2-win-x64.zip from cache
Extracting Feishin-0.21.2-win-x64.zip ... done.
Linking ~\scoop\apps\feishin\current => ~\scoop\apps\feishin\0.21.2
Creating shortcut for Feishin (Feishin.exe)
'feishin' (0.21.2) was installed successfully!
Updating 'imagemagick' (7.1.2-5 -> 7.1.2-7)
Downloading new version
OperationStopped: C:\Users\philipp.kretzschmar\scoop\apps\scoop\current\lib\down                                                                                                              load.ps1:84
Line |
  84 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

---

```
$ scoop -v
Current Scoop version:
b588a06e (HEAD -> master, tag: v0.5.3, origin/master, origin/HEAD) chore(release): Bump to version 0.5.3 (resync) (#6436)

'main' bucket:
cff4aae1c (HEAD -> master, origin/master, origin/HEAD) less: Update to version 685

'extras' bucket:
ddf7c6206c (HEAD -> master, origin/master, origin/HEAD) cpu-z@2.17: Fix hash (Closes #16338)

'nerd-fonts' bucket:
8a3064aa (HEAD -> master, origin/master, origin/HEAD) LXGWNeoZhiSong: Update to version 1.040
```

**Comment by k0pernikus** [comment]
I did the same as @xiaoxstz to print the inner exception:

```
scoop update imagemagick
imagemagick: 7.1.2-5 -> 7.1.2-7
Updating one outdated app:
Updating 'imagemagick' (7.1.2-5 -> 7.1.2-7)
Downloading new version
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
OperationStopped: C:\Users\philipp.kretzschmar\scoop\apps\scoop\current\lib\download.ps1:85
Line |
  85 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

**Comment by k0pernikus** [comment]
The issue persisted for a couple of days on only one machine, today it fixed itself after running

`scoop update`

and then 

`scoop update -a`

**Comment by k0pernikus** [comment]
Today, I see this behavior on another machine.


```
PS C:\Users\philipp> scoop update -a
pycharm-latest: 2026.1-261.20869.49 -> 2026.1-261.23567.80
ruby: 4.0.1-1 -> 4.0.3-1
unigetui: 3.3.7 -> 2026.1.6
warp-terminal: 0.2026.02.18.08.22.stable_02 -> 0.2026.04.15.08.45.stable_03
wave-terminal: 0.14.0 -> 0.14.5
windows-terminal-preview: 1.24.10212.0 -> 1.25.923.0
Updating 6 outdated apps:
Updating 'pycharm-latest' (2026.1-261.20869.49 -> 2026.1-261.23567.80)
Downloading new version
OperationStopped: C:\Users\philipp\scoop\apps\scoop\current\lib\download.ps1:84
Line |
  84 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

Might be related to a to tight pihole config, or maybe my IP has been rate limited as I had huge backlog for updates on this machine.

**Comment by k0pernikus** [comment]
Just found out that one can call

```
> $Error[0].Exception.InnerException | Format-List * -Force
```

Right after the failing command to see the inner exception:

```
OperationStopped: C:\Users\philipp\scoop\apps\scoop\current\lib\download.ps1:84
Line |
  84 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
PS C:\Users\philipp> $Error[0].Exception.InnerException | Format-List * -Force

TargetSite     : Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)
Message        : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
Data           : {}
InnerException : System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
HelpLink       :
Source         : System.Net.Sockets
HResult        : -2146232800
StackTrace     :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
                    at
                 System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16
                 token)
                    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
                    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSour
                 ce<TResult>.GetResult(Int16 token)
                    at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
                    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData,
                 CancellationToken cancellationToken)
                    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request,
                 Boolean async, Stream stream, CancellationToken cancellationToken)
```

Not sure if helpful at all, please let me know if I could provide other information.


This may make https://github.com/ScoopInstaller/Scoop/issues/6523 redundant.

**Comment by k0pernikus** [comment]
Might be windows networking issue rtather than scoop:

```
PS C:\Users\philipp> [Net.ServicePointManager]::SecurityProtocol = "Tls13"
PS C:\Users\philipp> Invoke-WebRequest -Uri "https://download.jetbrains.com" -Method Head
Invoke-WebRequest: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
```


---

Google works:

```
 Invoke-WebRequest -Uri "https://www.google.com" -Method Head | Select-Object StatusCode, StatusDescription, Headers

StatusCode StatusDescription Headers
---------- ----------------- -------
       200 OK                {[Content-Security-Policy-Report-Only, System.String[]], [Accept-CH, System.String[]], [P3P, System.String[]], [Date, System.…

```

**Comment by k0pernikus** [comment]
I added `aria2` which scoop uses automatically, and I was able to download the packages that way.

```
> scoop install aria2
```

```
> scoop update -a
pycharm-latest: 2026.1-261.20869.49 -> 2026.1-261.23567.80
ruby: 4.0.1-1 -> 4.0.3-1
unigetui: 3.3.7 -> 2026.1.6
warp-terminal: 0.2026.02.18.08.22.stable_02 -> 0.2026.04.15.08.45.stable_03
wave-terminal: 0.14.0 -> 0.14.5
windows-terminal-preview: 1.24.10212.0 -> 1.25.923.0
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Updating 6 outdated apps:
Updating 'pycharm-latest' (2026.1-261.20869.49 -> 2026.1-261.23567.80)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c551c7|OK  |    48MiB/s|C:/Users/philipp/scoop/cache/pycharm-latest#2026.1-261.23567.80#950c57f.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of pycharm-261.23567.80.exe ... ok.
Uninstalling 'pycharm-latest' (2026.1-261.20869.49)
Removing shim 'pycharm.shim'.
Removing shim 'pycharm.exe'.
Unlinking ~\scoop\apps\pycharm-latest\current
Installing 'pycharm-latest' (2026.1-261.23567.80) [64bit] from 'versions' bucket
Loading pycharm-261.23567.80.exe from cache.
Extracting pycharm-261.23567.80.exe ... done.
Running installer script...done.
Linking ~\scoop\apps\pycharm-latest\current => ~\scoop\apps\pycharm-latest\2026.1-261.23567.80
Creating shim for 'pycharm'.
Making C:\Users\philipp\scoop\shims\pycharm.exe a GUI binary.
Creating shortcut for JetBrains\PyCharm (Latest) (pycharm64.exe)
Persisting IDE\bin\idea.properties
Persisting IDE\bin\pycharm64.exe.vmoptions
Persisting profile
'pycharm-latest' (2026.1-261.23567.80) was installed successfully!
Notes
...
```
